apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-gke-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-gke
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
