apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-gke
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
