apiVersion: v1
kind: Service
metadata:
  name: probe
spec: LoadBalancer
  type:
  selector:
    app: probe
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
      - name: probe
        image: gcr.io/geekbang-gke/hello:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
           path: /healths
           port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
     
